///////////////////////////////////////////////////////////////////////////////
// CSyncModulesClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "CSyncModulesClassFactory.h"
#include "CSyncModulesServices.h"
#include "CSyncModulesVersion.h"
#include "Main.h"

BEGIN_CLASS_MAP(CCSyncModulesClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_CSyncModulesCMain, SRVNAME_CSYNCMODULES "!CMain", CMain)
///</AutoGeneratedContent>
END_CLASS_MAP()

CCSyncModulesClassFactory::CCSyncModulesClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_CSYNCMODULES));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(CSyncModules));
#endif //defined(TCDBG_UNIT_VERSION)
}

