///////////////////////////////////////////////////////////////////////////////
// CSyncModulesInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "CSyncModulesServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
