///////////////////////////////////////////////////////////////////////////////
// CSyncModulesServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_CSyncModules = 0x3F000000;
#define SRVNAME_CSYNCMODULES "CSyncModules"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_CSyncModulesCMain = {0xac9b0c3e,0xdadb,0x4f75,{0x96,0x9b,0x9e,0xf9,0xe8,0x2a,0x15,0x85}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_MainParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _MainParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} MainParameter, *PMainParameter;

typedef struct _MainInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} MainInputs, *PMainInputs;

typedef struct _MainOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} MainOutputs, *PMainOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_MainInputs 0
#define ADI_MainOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
