<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_SlaveCart" Id="{05baaa0e-c853-48bc-a37c-d593cfa5bf2b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SlaveCart
VAR
	//  TEST IO , just for IO link to enable ethercat 
	m_testInput AT%I* :ARRAY[1..10]  OF UINT;
	m_testOnput AT%q* :ARRAY[1..10]  OF UINT;
	m_testIO1 AT%I* :BOOL;
	m_testIO2 AT%I* :BOOL;
	m_testIO3 AT%Q* :UINT;
	m_testIO4 AT%I* :UINT;
	m_testIO5 AT%Q* :UINT;

	
	// cart status
	m_cartStatus  : ST_CartStatus;

	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="property" Id="{37b9f91a-fbe1-4cae-807d-574d49e247d7}" />
    <Method Name="init" Id="{a9830b95-e937-4a29-b70e-785e20452d37}">
      <Declaration><![CDATA[METHOD init : BOOL
VAR_INPUT
END_VAR
VAR
	i:INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
]]></ST>
      </Implementation>
    </Method>
    <Method Name="run" Id="{5adedbe6-c484-4199-b427-bc8af7c6d1b0}">
      <Declaration><![CDATA[METHOD run : BOOL
VAR_INPUT
END_VAR
VAR
	i:INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="status" Id="{cd2a750f-147a-42a5-85cd-a7d5a815c963}" FolderPath="property\">
      <Declaration><![CDATA[PROPERTY status : ST_CartStatus]]></Declaration>
      <Get Name="Get" Id="{c1788322-40e1-4e3e-a26b-a8239c1e1e6d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[status := m_cartStatus;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="updateCmds" Id="{a083537e-6f52-4b88-8b83-3c9a5d0db87a}">
      <Declaration><![CDATA[METHOD updateCmds : BOOL
VAR_INPUT
END_VAR
VAR
	i:INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="updateStatus" Id="{7dc0698e-0910-43df-8937-4fb176791915}">
      <Declaration><![CDATA[METHOD updateStatus : BOOL
VAR_INPUT
END_VAR
VAR
	i:INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SlaveCart">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_SlaveCart.init">
      <LineId Id="32" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_SlaveCart.run">
      <LineId Id="19" Count="0" />
    </LineIds>
    <LineIds Name="FB_SlaveCart.status.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_SlaveCart.updateCmds">
      <LineId Id="20" Count="0" />
    </LineIds>
    <LineIds Name="FB_SlaveCart.updateStatus">
      <LineId Id="16" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>