///////////////////////////////////////////////////////////////////////////////
// CSyncModuleInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "CSyncModuleServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
