///////////////////////////////////////////////////////////////////////////////
// CSyncModuleClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "CSyncModuleClassFactory.h"
#include "CSyncModuleServices.h"
#include "CSyncModuleVersion.h"
#include "Main.h"

BEGIN_CLASS_MAP(CCSyncModuleClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_CSyncModuleCMain, SRVNAME_CSYNCMODULE "!CMain", CMain)
///</AutoGeneratedContent>
END_CLASS_MAP()

CCSyncModuleClassFactory::CCSyncModuleClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_CSYNCMODULE));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(CSyncModule));
#endif //defined(TCDBG_UNIT_VERSION)
}

