///////////////////////////////////////////////////////////////////////////////
// CSyncModuleServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_CSyncModule = 0x3F000000;
#define SRVNAME_CSYNCMODULE "CSyncModule"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_CSyncModuleCMain = {0xa658d956,0x3b5e,0x457b,{0xa7,0x2f,0x17,0x9c,0x6e,0x73,0xee,0x06}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_MainParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _MainParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} MainParameter, *PMainParameter;

typedef struct _MainInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} MainInputs, *PMainInputs;

typedef struct _MainOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} MainOutputs, *PMainOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_MainInputs 0
#define ADI_MainOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
