<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_SetupArmCheck" Id="{e758489d-b7ab-4083-a13e-e0865f9223c6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SetupArmCheck
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_SetupArmCheck">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>