<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_SetupCtrlHold" Id="{acc6ed82-034a-420c-8162-3225c33c4b38}" SpecialFunc="None">
    <Declaration><![CDATA[// Brief: Setup Arm Init
FUNCTION_BLOCK PUBLIC FB_SetupCtrlHold EXTENDS FB_SetupArmCtrlBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	m_initState :INT :=0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <LineIds Name="FB_SetupCtrlHold">
      <LineId Id="18" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>