<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_SetupCtrlCart" Id="{4fa06658-3c16-4ac9-904b-65722ac0872f}" SpecialFunc="None">
    <Declaration><![CDATA[// Brief: setup Arm Cart Control
FUNCTION_BLOCK PUBLIC FB_SetupCtrlCart EXTENDS FB_SetupArmCtrlBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_SetupCtrlCart">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>