<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_SlaveCtrlCart" Id="{acf69b98-a94c-45d6-930a-e719a9a02026}" SpecialFunc="None">
    <Declaration><![CDATA[// Brief: Slave Arm Cart Control
FUNCTION_BLOCK PUBLIC FB_SlaveCtrlCart EXTENDS FB_SlaveArmCtrlBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="init" Id="{4c46dc31-dc49-4fc6-9e65-f4bc803697a8}">
      <Declaration><![CDATA[METHOD PUBLIC init : BOOL
VAR_IN_OUT CONSTANT
	i_slaveArm	:FB_SlaveArm;
END_VAR
VAR_IN_OUT 
	r_slaveArmCtrlCmd :ST_SlaveArmCtrlCmds;
END_VAR

VAR
	j:INT;
	maxJntErr:LREAL;
	jntCtrlErr:Vec7d;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// check if to hold the command joint position unchanged
m_holdLastCmds := checkToHoldLastCmds(i_slaveArm);

//init
SUPER^.Init(i_slaveArm,r_slaveArmCtrlCmd);]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SlaveCtrlCart">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_SlaveCtrlCart.init">
      <LineId Id="72" Count="3" />
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>