<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_SlaveCtrlInstruReady" Id="{b4863c0c-c549-4967-ab29-6a1152ef3cd8}" SpecialFunc="None">
    <Declaration><![CDATA[// Brief: Instrument Ready
FUNCTION_BLOCK PUBLIC FB_SlaveCtrlInstruReady EXTENDS FB_SlaveArmCtrlBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="init" Id="{2537cbc9-bbc0-4d20-a9bf-3a888748c955}">
      <Declaration><![CDATA[METHOD PUBLIC init : BOOL
VAR_IN_OUT CONSTANT
	i_slaveArm	:FB_SlaveArm;
END_VAR
VAR_IN_OUT 
	r_slaveArmCtrlCmd :ST_SlaveArmCtrlCmds;
END_VAR


VAR
	j:INT;
	maxJntErr:LREAL;
	jntCtrlErr:Vec7d;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[//NOTE:DO NOT hold last command

//init
SUPER^.Init(i_slaveArm,r_slaveArmCtrlCmd);]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SlaveCtrlInstruReady">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_SlaveCtrlInstruReady.init">
      <LineId Id="91" Count="0" />
      <LineId Id="93" Count="0" />
      <LineId Id="76" Count="0" />
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>