<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_SlaveGravity" Id="{ced9fef1-3691-440d-9914-43fe53d631cd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SlaveGravity
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	// arm index
	m_armIdx :INT;
	
	(*graParam=[ 2.7244*m3 + 2.7244*m4 + 2.7244*m5 + 2.7244*m6 + 9.8*mx2 + 9.8*mx9,
            	9.8*my2 + 9.8*my9,
			 	3.577*m4 + 3.577*m5 + 3.577*m6 + 0.49*m9 + 9.8*mx3 + 9.8*mx8
           		1.5827*m4 + 1.5827*m5 + 1.5827*m6 + 9.8*my3 + 9.8*my8 + 9.8*mz4
            	mz5-my4,	my5+mz6,  	mx4,   	mx5, 	mx6,   	my6
            	preF2,   k2,   preF3,    k3,    preF5   k5]*)
	m_gravityParam :ARRAY[1..16] OF REAL;
	// spring2 [L0, b1, b2, l1, r0]
	m_spring2Param :ARRAY[1..5] OF LREAL;
	// spring3 [L0, b1, b2, l1, r0,d]
	m_spring3Param :ARRAY[1..6] OF LREAL;
	// spring5 [L0, s1, L1, r0, beta]
	m_spring5Param :ARRAY[1..5] OF LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="init" Id="{e7795345-42d8-4dbc-8eda-5e489420b6e1}">
      <Declaration><![CDATA[METHOD PUBLIC init : BOOL
VAR_INPUT
	i_armIdx :INT;
END_VAR
VAR
	i:INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[m_armIdx:=i_armIdx;

]]></ST>
      </Implementation>
    </Method>
    <Method Name="run" Id="{469433a3-9614-4c99-9efb-b9558878df36}">
      <Declaration><![CDATA[METHOD PUBLIC run : BOOL
VAR_IN_OUT CONSTANT
	// slave arm joint position
	i_jntPos :vec8d;
	
	// set up distal end frame
	i_setArmFrame : ST_Frame;
END_VAR
VAR_IN_OUT
	r_gravity :Vec3d;
END_VAR
VAR


END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[r_gravity := g_zeroVec3d;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SlaveGravity">
      <LineId Id="75" Count="0" />
    </LineIds>
    <LineIds Name="FB_SlaveGravity.init">
      <LineId Id="18" Count="1" />
      <LineId Id="17" Count="0" />
    </LineIds>
    <LineIds Name="FB_SlaveGravity.run">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>