<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_SetupCtrlDisable" Id="{fd37dfd1-46dd-4a23-a295-d8873104bc66}" SpecialFunc="None">
    <Declaration><![CDATA[// Brief: Setup Arm Error Hold
FUNCTION_BLOCK PUBLIC FB_SetupCtrlDisable EXTENDS FB_SetupArmCtrlBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_SetupCtrlDisable">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>