<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_SetupCtrlHold" Id="{acc6ed82-034a-420c-8162-3225c33c4b38}" SpecialFunc="None">
    <Declaration><![CDATA[// Brief: Setup Arm Init
FUNCTION_BLOCK PUBLIC FB_SetupCtrlHold EXTENDS FB_SetupArmCtrlBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	m_initState :INT :=0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <Method Name="init" Id="{19914e93-fefd-4af6-8135-c232cbfbf440}">
      <Declaration><![CDATA[// override this function in each exact controller
// NOTICE: set joint control mode here, and do some initialization if needed
METHOD PUBLIC init : BOOL
VAR_IN_OUT CONSTANT
	i_setupArm	:FB_SetupArm;
END_VAR
VAR_IN_OUT 
	r_setupArmCtrlCmd :ST_SetupArmCtrlCmds;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.Init(i_setupArm,r_setupArmCtrlCmd);

// TODO: setup joint3 would "jump" a bit when transit from torque mode to position mode
m_jntOPMode[3] := DriverOPMode_Trq;
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SetupCtrlHold">
      <LineId Id="18" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_SetupCtrlHold.init">
      <LineId Id="104" Count="0" />
      <LineId Id="107" Count="0" />
      <LineId Id="106" Count="0" />
      <LineId Id="105" Count="0" />
      <LineId Id="83" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>