<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_SetupCtrlSelfCheck" Id="{de863df1-4a4d-4fa9-a2ab-b3b6dd7ec2a1}" SpecialFunc="None">
    <Declaration><![CDATA[// Brief: Setup Arm Self-check
FUNCTION_BLOCK PUBLIC FB_SetupCtrlSelfCheck EXTENDS FB_SetupArmCtrlBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR

	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="init" Id="{57d7becd-4a0a-4f37-8764-94cf78ff725a}">
      <Declaration><![CDATA[METHOD PUBLIC init : BOOL
VAR_IN_OUT CONSTANT
	i_setupArm	:FB_SetupArm;
END_VAR
VAR_IN_OUT 
	r_setupArmCtrlCmd :ST_SetupArmCtrlCmds;
END_VAR


]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.Init(i_setupArm,r_setupArmCtrlCmd);

// TODO: add selfcheck laster if needed, currently finish directly
m_isFinished := true;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SetupCtrlSelfCheck">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_SetupCtrlSelfCheck.init">
      <LineId Id="57" Count="0" />
      <LineId Id="136" Count="0" />
      <LineId Id="126" Count="0" />
      <LineId Id="137" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>