///////////////////////////////////////////////////////////////////////////////
// CADSModuleClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "CADSModuleClassFactory.h"
#include "CADSModuleServices.h"
#include "CADSModuleVersion.h"
#include "Main.h"

BEGIN_CLASS_MAP(CCADSModuleClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_CADSModuleCMain, SRVNAME_CADSMODULE "!CMain", CMain)
///</AutoGeneratedContent>
END_CLASS_MAP()

CCADSModuleClassFactory::CCADSModuleClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_CADSMODULE));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(CADSModule));
#endif //defined(TCDBG_UNIT_VERSION)
}

