///////////////////////////////////////////////////////////////////////////////
// CADSModuleServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_CADSModule = 0x3F000000;
#define SRVNAME_CADSMODULE "CADSModule"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_CADSModuleCMain = {0x0e481ab9,0x7bf0,0x4b56,{0xab,0x95,0x99,0x18,0x81,0x77,0x2e,0x5f}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_MainDefaultAdsPort = 0x00000001;
const PTCID PID_MainCounter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _MainInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} MainInputs, *PMainInputs;

typedef struct _MainOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} MainOutputs, *PMainOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_MainInputs 0
#define ADI_MainOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
